export const adminPage = {
  en: {
    adminPage: {
      title: "Admin",
      tabs: {
        dashboard: "Dashboard",
        registrations: "Registrations",
        teams: "Teams",
        matches: "Matches",
        ball: "Ball",
        players: "Players",
        categories: "Category",
        prizes: "Prizes",
        admins: "Admin users",
        courtBookings: "Court bookings",
        tumblers: "Giveaways",
        media: "Media",
      },
      navGroups: {
        operations: "Operations",
        tournamentSetup: "Tournament Setup",
        entries: "Entries",
      },
      dashboard: {
        yearLabel: "Year",
        prelimRoundLabel: "Prelim",
        noData: "No data yet",
        tabs: { thisYear: "This year", allTime: "All time" },
        totalLabel: "Total {count} {label}",
        matchesUnitLabel: "matches",
        teamsUnitLabel: "teams",
        pointsUnitLabel: "pts",
        overview: {
          completedMatches: "Completed matches",
          registrations: "Registrations",
          registrationsSubtitle: "Registration status breakdown for this year",
          teams: "Teams",
          teamsByCategory: {
            title: "Teams by category",
            subtitle: "Team count by category for this year",
          },
        },
        matchProgress: {
          completionOverTime: {
            title: "Match completion over time",
            subtitle: "Matches completed as of today",
          },
          completionByRound: {
            title: "Completion by round",
            subtitle:
              "Percentage of matches completed in each tournament round",
          },
        },
        clubPerformance: {
          winningClubs: {
            title: "Winning clubs",
            subtitle: "Clubs ranked by match wins for the selected round",
          },
          participation: {
            title: "Club participation",
            subtitle:
              "Clubs ranked by number of confirmed registrations for this year",
          },
          championship: {
            title: "Club championship points",
            subtitle:
              "Club total points calculated based on participation and match results",
            legend: {
              participation: "Participation (1 pt)",
              semifinal: "Semifinal (5 pts)",
              runnerUp: "Runner-up (20 pts)",
              champion: "Champion (50 pts)",
            },
          },
          allRounds: "All rounds",
        },
        allTime: {
          registrationGrowth: {
            title: "Player registrations by year",
            subtitle: "Total registered players for each tournament year",
          },
          teamsGrowth: {
            title: "Teams by year",
            subtitle: "Total participating teams for each tournament year",
          },
          teamGrowth: {
            title: "Teams by category over time",
            subtitle:
              "Year-over-year changes in participating teams by category",
          },
          clubPerformanceHistory: {
            title: "Club performance",
            subtitle: "Club rankings by total wins for the selected year",
          },
          clubParticipationHistory: {
            title: "Club participation by year",
            subtitle:
              "Confirmed registrations by club for each tournament year",
          },
          allTimeLabel: "All time",
        },
      },
      actions: {
        addRegistration: "Add Registration",
        addPlayer: "Add Player",
        addAdminUser: "Add admin",
        addPhoto: "Add photo",
        save: "Save",
        saving: "Saving…",
        saveAndGenerate: "Save & Generate",
        generating: "Generating…",
        cancel: "Cancel",
        delete: "Delete",
        deleting: "Deleting…",
        add: "Add",
        adding: "Adding…",
        close: "Close",
        yes: "Yes",
        no: "No",
      },
      registrations: {
        empty: "No registrations",
        columns: {
          player: "Player",
          partner: "Partner",
          score: "Score",
          payment: "Payment",
          notes: "Notes",
          tumbler: "Tumbler",
        },
        modal: {
          title: "Manage Registration",
          addTitle: "Add Registration",
          playerSection: "Player",
          name: "Name (EN)",
          nameKo: "Name (KO)",
          partnerName: "Partner Name",
          nameOnEtransfer: "Name on e-Transfer",
          photoConsent: "Photo / video consent",
          notes: "Notes",
          category: "Category",
          paymentReceived: "Payment received",
          adminComments: "Admin comments",
        },
      },
      teams: {
        empty: "No teams",
        columns: {
          number: "#",
          player1: "Player 1",
          player2: "Player 2",
        },
        seedModal: {
          title: "Seed Teams",
          year: "Year",
          prelimFormat: "Prelim Format",
          roundRobin: "Round Robin",
          groupRoundRobin: "Group Round Robin",
          elimination: "Elimination",
          numberOfGroups: "Number of groups",
          selectTeamsPlaceholder: "Select teams…",
          seedLabel: "Seed",
          teamsCount: "teams",
          locked:
            "Seeding is locked — draws have already been published for this year",
        },
      },
      matches: {
        empty: "No matches",
        columns: {
          matchId: "Match",
          team1: "Team 1",
          team2: "Team 2",
          round: "Round",
          score: "Score",
          sets: "Sets",
          time: "Time",
          location: "Location",
        },
        modal: {
          title: "Edit Match",
          status: "Status",
          scoresSection: "Scores",
          set1: "Set 1",
          set2: "Set 2",
          set3: "Set 3",
          cancelled: "Cancelled",
          walkover: "Walkover",
          date: "Date",
          time: "Time",
          location: "Location",
          ball: "Ball",
          comment: "Comment",
        },
      },
      players: {
        empty: "No players",
        columns: {
          clubs: "Clubs",
          tournaments: "Tournaments",
        },
        modal: {
          editTitle: "Edit Player",
          addTitle: "Add Player",
          cannotDeleteTitle: "Cannot Delete Player",
        },
      },
      categories: {
        empty: "No categories",
        columns: {
          label: "Category",
          status: "Status",
          teams: "Teams",
        },
        modal: {
          editTitle: "Edit Category",
          statusLabel: "Status",
          playersTitle: "Registered Players",
          noPlayers: "No registrations for this category.",
          prelimFormat: "Prelim Format",
          roundRobin: "Round Robin",
          groupRoundRobin: "Group Round Robin",
          elimination: "Elimination",
        },
      },
      prizes: {
        empty: "No prize data",
        teamsUnit: "teams",
        bracketSuffix: "bracket",
        saveError: "Save failed",
        columns: {
          category: "Category",
          teams: "Teams",
          first: "1st",
          second: "2nd",
          third: "3rd",
          fourth: "4th",
          total: "Total",
        },
        modal: {
          title: "Edit Prize",
        },
      },
      admins: {
        empty: "No admin users",
        columns: {
          active: "Status",
          created: "Created",
        },
        activeLabel: "Active",
        inactiveLabel: "Inactive",
        modal: {
          editTitle: "Edit Admin User",
          addTitle: "Add Admin User",
          note: "The admin will set their password on first login.",
        },
      },
      courtBookings: {
        dateLabel: "Date",
        empty: "No courts",
        notAvailableLabel: "Not available",
        availableLabel: "Available",
        bookedLabel: "Booked",
        matchLabel: "Match",
        searchMatchPlaceholder: "Search by player name…",
        searchMatchLoading: "Searching…",
        searchMatchEmpty: "No matches found",
        saveError: "Save failed — please try again.",
        columns: {
          court: "Court",
          status: "Status",
          bookedBy: "Booked by",
          teams: "Teams",
        },
        manageTitle: "Manage booking",
        courtBookingNotesLabel: "Notes",
        matchSearchPlaceholder: "Enter player name to find match",
        cancelBookingLabel: "Cancel Booking",
      },
      tumblers: {
        columns: {
          tumbler: "Tumbler",
          stock: "Stock",
          status: "Status",
          player: "Player",
          tumblerChoice: "Tumbler",
          received: "Received",
          pickup: "Pickup club",
          pickupDetails: "Pickup details",
        },
        statusAvailable: "Available",
        statusFull: "Full",
        otherClub: "Other",
        noApplicants: "No applicants",
        pickupOtherPrefix: "Other",
        summaryTitle: "Distribution summary",
        inventoryTab: "Inventory",
        selectionsTab: "Selections",
        optionFilterPlaceholder: "Option",
        optionFilterUnitLabel: "options",
        searchPlaceholder: "Search by player name",
      },
      ball: {
        empty: "No balls assigned",
        rowCountSingular: "ball",
        rowCountPlural: "balls",
        columns: {
          player: "Player",
          date: "Date",
          match: "Match",
          received: "Received",
        },
      },
      media: {
        subTabs: {
          articles: "Articles",
          videos: "Videos",
          photos: "Photos",
          photoAlbum: "Photo Album",
        },
        addButton: "Add",
        addButtons: {
          articles: "Add article",
          videos: "Add video",
          photos: "Add photo",
        },
        empty: "No items",
        columns: {
          image: "Image",
          title: "Title",
          type: "Type",
          date: "Date",
          sortOrder: "Order",
          nickname: "Nickname",
          caption: "Caption",
          views: "Views",
          likes: "Likes",
          comments: "Comments",
          award: "Award",
        },
        fields: {
          title: "Title (EN)",
          titleKo: "Title (KO)",
          subtitle: "Subtitle (EN)",
          subtitleKo: "Subtitle (KO)",
          image: "Image URL",
          media: "Media URL",
          outlet: "Outlet (EN)",
          outletKo: "Outlet (KO)",
          date: "Date",
          category: "Category",
          noCategory: "None",
          sortOrder: "Sort order",
          tournamentYear: "Tournament year",
        },
        modal: {
          addTitle: "Add Media",
          editTitle: "Edit Media",
          photoAlbumTitle: "Photo submission",
          toggleAward: "Toggle Best Photo Award",
          awardOn: "Best Photo Award ✓",
          awardOff: "Mark as Best Photo Award",
          deleteConfirmTitle: "Delete this photo?",
        },
        awardLabel: "Award",
      },
    },
  },
  ko: {
    adminPage: {
      title: "관리자 메뉴",
      tabs: {
        dashboard: "대시보드",
        registrations: "등록",
        teams: "팀",
        matches: "경기",
        ball: "공",
        players: "선수",
        categories: "카테고리",
        prizes: "상금",
        admins: "관리자 계정",
        courtBookings: "코트 예약",
        tumblers: "참가 상품",
        media: "미디어",
      },
      navGroups: {
        operations: "운영",
        tournamentSetup: "대회 설정",
        entries: "참가",
      },
      dashboard: {
        yearLabel: "연도",
        prelimRoundLabel: "예선",
        noData: "데이터 없음",
        tabs: { thisYear: "올해", allTime: "전체 기간" },
        totalLabel: "총 {count} {label} 중",
        matchesUnitLabel: "경기",
        teamsUnitLabel: "팀",
        pointsUnitLabel: "점",
        overview: {
          completedMatches: "완료된 경기",
          registrations: "등록",
          registrationsSubtitle: "올해 참가 등록 현황",
          teams: "팀",
          teamsByCategory: { title: "카테고리별 팀 수", subtitle: "" },
        },
        matchProgress: {
          completionOverTime: {
            title: "기간별 경기 완료 추이",
            subtitle: "전체 경기 기준 금일 완료 현황",
          },
          completionByRound: {
            title: "라운드별 경기 완료율",
            subtitle: "전체 경기 중 각 라운드에서 완료된 경기 비율",
          },
        },
        clubPerformance: {
          winningClubs: {
            title: "클럽 성과",
            subtitle: "선택한 라운드의 클럽별 승수 순위",
          },
          participation: {
            title: "클럽 참여 현황",
            subtitle: "올해 확정 등록 수 기준 클럽 순위",
          },
          championship: {
            title: "클럽 종합 순위",
            subtitle: "참가 및 경기 성과를 기준으로 산정된 클럽별 종합 점수",
            legend: {
              participation: "참가 (1점)",
              semifinal: "4강 진출 (5점)",
              runnerUp: "준우승 (20점)",
              champion: "우승 (50점)",
            },
          },
          allRounds: "전체 라운드",
        },
        allTime: {
          registrationGrowth: {
            title: "연도별 선수 등록 현황",
            subtitle: "대회 연도별 전체 등록 선수 수",
          },
          teamsGrowth: {
            title: "연도별 전체 팀 수",
            subtitle: "대회 연도별 전체 참가 팀 수",
          },
          teamGrowth: {
            title: "연도별 카테고리별 팀 수 추이",
            subtitle: "각 카테고리의 연도별 참가 팀 수 변화",
          },
          clubPerformanceHistory: {
            title: "클럽별 성과",
            subtitle: "선택한 연도의 클럽별 전체 승리 순위",
          },
          clubParticipationHistory: {
            title: "연도별 클럽 참여 현황",
            subtitle: "대회 연도별 클럽별 확정 등록 수",
          },
          allTimeLabel: "전체 기간",
        },
      },
      actions: {
        addRegistration: "등록 추가",
        addPlayer: "선수 추가",
        addAdminUser: "관리자 추가",
        addPhoto: "사진 추가",
        save: "저장",
        saving: "저장 중…",
        saveAndGenerate: "저장 및 생성",
        generating: "생성 중…",
        cancel: "취소",
        delete: "삭제",
        deleting: "삭제 중…",
        add: "추가",
        adding: "추가 중…",
        close: "닫기",
        yes: "예",
        no: "아니오",
      },
      registrations: {
        empty: "등록 내역 없음",
        columns: {
          player: "선수",
          partner: "파트너",
          score: "점수",
          payment: "결제",
          notes: "메모",
          tumbler: "텀블러",
        },
        modal: {
          title: "등록 관리",
          addTitle: "등록 추가",
          playerSection: "선수",
          name: "이름 (EN)",
          nameKo: "이름 (KO)",
          partnerName: "파트너 이름",
          nameOnEtransfer: "이체 시 이름",
          photoConsent: "사진/영상 동의",
          notes: "메모",
          category: "카테고리",
          paymentReceived: "결제 완료",
          adminComments: "관리자 메모",
        },
      },
      teams: {
        empty: "팀 없음",
        columns: {
          number: "#",
          player1: "선수 1",
          player2: "선수 2",
        },
        seedModal: {
          title: "팀 시드 배정",
          year: "연도",
          prelimFormat: "예선 포맷",
          roundRobin: "라운드 로빈",
          groupRoundRobin: "그룹 라운드 로빈",
          elimination: "토너먼트",
          numberOfGroups: "그룹 수",
          selectTeamsPlaceholder: "팀 선택…",
          seedLabel: "시드",
          teamsCount: "팀",
          locked: "시드 배정이 잠겼습니다 — 올해 대진표가 이미 발표되었습니다",
        },
      },
      matches: {
        empty: "경기 없음",
        columns: {
          matchId: "경기",
          team1: "팀 1",
          team2: "팀 2",
          round: "라운드",
          score: "점수",
          sets: "세트",
          time: "시간",
          location: "장소",
        },
        modal: {
          title: "경기 편집",
          status: "상태",
          scoresSection: "점수",
          set1: "1세트",
          set2: "2세트",
          set3: "3세트",
          cancelled: "취소",
          walkover: "기권",
          date: "날짜",
          time: "시간",
          location: "장소",
          ball: "공",
          comment: "비고",
        },
      },
      players: {
        empty: "선수 없음",
        columns: {
          clubs: "클럽",
          tournaments: "대회 참가",
        },
        modal: {
          editTitle: "선수 편집",
          addTitle: "선수 추가",
          cannotDeleteTitle: "선수를 삭제할 수 없습니다",
        },
      },
      categories: {
        empty: "카테고리 없음",
        columns: {
          label: "카테고리",
          status: "상태",
          teams: "팀",
        },
        modal: {
          editTitle: "카테고리 편집",
          statusLabel: "상태",
          playersTitle: "등록된 선수",
          noPlayers: "이 카테고리에 등록된 선수가 없습니다.",
          prelimFormat: "예선 포맷",
          roundRobin: "라운드 로빈",
          groupRoundRobin: "그룹 라운드 로빈",
          elimination: "토너먼트",
        },
      },
      prizes: {
        empty: "상금 데이터 없음",
        teamsUnit: "팀",
        bracketSuffix: "구간",
        saveError: "저장 실패",
        columns: {
          category: "카테고리",
          teams: "팀",
          first: "1위",
          second: "2위",
          third: "3위",
          fourth: "4위",
          total: "합계",
        },
        modal: {
          title: "상금 편집",
        },
      },
      admins: {
        empty: "관리자 계정 없음",
        columns: {
          active: "상태",
          created: "생성일",
        },
        activeLabel: "활성",
        inactiveLabel: "비활성",
        modal: {
          editTitle: "관리자 편집",
          addTitle: "관리자  추가",
          note: "관리자는 첫 로그인 시 비밀번호를 설정합니다.",
        },
      },
      courtBookings: {
        dateLabel: "날짜",
        empty: "코트 정보 없음",
        notAvailableLabel: "해당 없음",
        availableLabel: "예약 가능",
        bookedLabel: "예약됨",
        matchLabel: "경기",
        searchMatchPlaceholder: "선수 이름으로 검색…",
        searchMatchLoading: "검색 중…",
        searchMatchEmpty: "일치하는 경기가 없습니다",
        saveError: "저장에 실패했습니다 — 다시 시도해 주세요.",
        columns: {
          court: "코트",
          status: "상태",
          bookedBy: "예약자",
          teams: "팀",
        },
        manageTitle: "코트 예약 관리",
        courtBookingNotesLabel: "메모",
        matchSearchPlaceholder: "이름을 입력하여 경기를 검색하세요",
        cancelBookingLabel: "예약 취소",
      },
      tumblers: {
        columns: {
          tumbler: "텀블러",
          stock: "재고",
          status: "상태",
          player: "선수",
          tumblerChoice: "텀블러",
          received: "수령 완료",
          pickup: "수령 클럽",
          pickupDetails: "픽업 세부 정보",
        },
        statusAvailable: "가능",
        statusFull: "마감",
        otherClub: "기타",
        noApplicants: "신청자 없음",
        pickupOtherPrefix: "Other",
        summaryTitle: "분배 요약",
        inventoryTab: "재고",
        selectionsTab: "선택 현황",
        optionFilterPlaceholder: "옵션",
        optionFilterUnitLabel: "옵션",
        searchPlaceholder: "선수 이름으로 검색",
      },
      ball: {
        empty: "배정된 공 없음",
        rowCountSingular: "공",
        rowCountPlural: "공",
        columns: {
          player: "선수",
          date: "날짜",
          match: "경기",
          received: "수령 완료",
        },
      },
      media: {
        subTabs: {
          articles: "기사",
          videos: "영상",
          photos: "사진",
          photoAlbum: "포토 앨범",
        },
        addButton: "추가",
        addButtons: {
          articles: "기사 추가",
          videos: "영상 추가",
          photos: "사진 추가",
        },
        empty: "항목이 없습니다",
        columns: {
          image: "이미지",
          title: "제목",
          type: "유형",
          date: "날짜",
          sortOrder: "순서",
          nickname: "닉네임",
          caption: "설명",
          views: "조회수",
          likes: "좋아요",
          comments: "댓글",
          award: "수상",
        },
        fields: {
          title: "제목 (영문)",
          titleKo: "제목 (한글)",
          subtitle: "부제목 (영문)",
          subtitleKo: "부제목 (한글)",
          image: "이미지 URL",
          media: "미디어 URL",
          outlet: "출처 (영문)",
          outletKo: "출처 (한글)",
          date: "날짜",
          category: "카테고리",
          noCategory: "없음",
          sortOrder: "정렬 순서",
          tournamentYear: "대회 연도",
        },
        modal: {
          addTitle: "미디어 추가",
          editTitle: "미디어 수정",
          photoAlbumTitle: "제출된 사진",
          toggleAward: "베스트 포토 어워드 전환",
          awardOn: "베스트 포토 어워드 ✓",
          awardOff: "베스트 포토 어워드로 지정",
          deleteConfirmTitle: "이 사진을 삭제하시겠습니까?",
        },
        awardLabel: "수상",
      },
    },
  },
} as const;
