export const adminPage = {
  en: {
    adminLogin: {
      title: "Admin sign in",
      invalidCredentials: "Invalid email or password.",
    },
    adminPage: {
      heroTitle: "Admin",
      tabs: {
        registrations: "Registrations",
        categories: "Categories",
        players: "Players",
        users: "Admins",
        matches: "Matches",
      },
      users: {
        email: "Email",
        createdOn: "Created On",
        status: "Status",
        active: "Active",
        inactive: "Inactive",
        total: (count: number) => `Total: ${count}`,
        addTitle: "Add admin",
        deleteTitle: "Remove admin?",
        deleteWarning: "This will remove the admin account. This cannot be undone.",
        delete: "Remove",
        deleting: "Removing…",
        saveFailed: "Save failed",
      },
    },
    adminPlayers: {
      addTitle: "Add player",
      editTitle: "Edit player",
      deleteTitle: "Delete player?",
      idLabel: "ID",
      deleteWarning:
        "Linked registrations will be removed. This may fail if the player is on a team used by matches.",
      save: "Save",
      saving: "Saving…",
      cancel: "Cancel",
      delete: "Delete",
      deleteEllipsis: "Delete",
      deleting: "Deleting",
      nameEn: "Name (English)",
      nameKo: "Name (Korean)",
      email: "Email",
      phone: "Phone",
      ntrp: "NTRP",
      clubs: "Club(s)",
      totalCount: (count: number) => `Total: ${count}`,
      noSearchResults: "No players match your search.",
      deleteFailed: "Delete failed",
    },
    adminMatches: {
      addTitle: "Add match",
      addModalTitle: "Add match",
      totalCount: (count: number) => `Total: ${count}`,
      emptyState: "No matches yet.",
      updateFailed: "Update failed",
      deleteFailed: "Delete failed",
      editMatchTitle: "Edit match",
      time: "Time",
      setScores: "Set scores",
      set1: "Set 1",
      set2: "Set 2",
      set3: "Set 3",
      comment: "Comment",
      save: "Save",
      saving: "Saving…",
      deleteEllipsis: "Delete…",
      deleteTitle: "Delete match?",
      deleteWarning: "This removes the match from the schedule. This cannot be undone.",
      delete: "Delete",
      deleting: "Deleting…",
      noLocations: "No locations",
      status: "Status",
      tableTeam1: "Team 1",
      tableTeam2: "Team 2",
      tableLocation: "Location",
      tableScore: "Score",
    },
    adminRegistrations: {
      addTitle: "Add registration",
      editModalTitle: "Edit registration",
      addModalTitle: "Add registration",
      deleteEllipsis: "Delete",
      deleteRegistration: "Delete",
      deleteModalTitle: "Delete registration?",
      deleteModalBody:
        "This will delete the category selected for this player. This cannot be undone.",
      deleteModalDeleting: "Deleting…",
      totalCount: (count: number) => `Total: ${count}`,
      tableRegNumber: "#",
      tablePartner: "Partner name",
      tableMediaConsent: "Media consent",
      tableEngraving: "Engraving",
      emptyState: "No registrations yet.",
    },
    categoryYears: {
      addTitle: "Add category",
      addModalTitle: "Add category",
      countLabel: (count: number) => `${count} categories`,
      emptyState: "No categories for this year.",
    },
  },

  ko: {
    adminLogin: {
      title: "관리자 로그인",
      invalidCredentials: "관리자로 등록되지 않은 이메일입니다.",
    },
    adminPage: {
      heroTitle: "관리자",
      tabs: {
        registrations: "등록",
        categories: "카테고리",
        players: "선수",
        users: "관리자",
        matches: "경기",
      },
      users: {
        email: "이메일",
        createdOn: "가입일",
        status: "상태",
        active: "활성",
        inactive: "비활성",
        total: (count: number) => `총 ${count}명`,
        addTitle: "관리자 추가",
        deleteTitle: "관리자를 삭제할까요?",
        deleteWarning: "이 관리자 계정이 삭제됩니다. 되돌릴 수 없습니다.",
        delete: "삭제",
        deleting: "삭제 중…",
        saveFailed: "저장에 실패했습니다",
      },
    },
    adminPlayers: {
      addTitle: "선수 추가",
      editTitle: "선수 수정",
      deleteTitle: "선수를 삭제할까요?",
      idLabel: "ID",
      deleteWarning:
        "연결된 등록이 삭제됩니다. 경기에 사용 중인 팀에 포함된 선수는 삭제되지 않을 수 있습니다.",
      save: "저장",
      saving: "저장 중",
      cancel: "취소",
      delete: "삭제",
      deleteEllipsis: "삭제",
      deleting: "삭제 중",
      nameEn: "이름 (영문)",
      nameKo: "이름 (한글)",
      email: "이메일",
      phone: "전화번호",
      ntrp: "NTRP",
      clubs: "클럽",
      totalCount: (count: number) => `총 ${count}명`,
      noSearchResults: "검색 결과가 없습니다.",
      deleteFailed: "삭제에 실패했습니다",
    },
    adminMatches: {
      addTitle: "경기 추가",
      addModalTitle: "경기 추가",
      totalCount: (count: number) => `총 ${count}경기`,
      emptyState: "이 카테고리에 경기가 없습니다.",
      updateFailed: "저장에 실패했습니다",
      deleteFailed: "삭제에 실패했습니다",
      editMatchTitle: "경기 수정",
      time: "시간",
      setScores: "세트 스코어",
      set1: "1세트",
      set2: "2세트",
      set3: "3세트",
      comment: "비고",
      save: "저장",
      saving: "저장 중…",
      deleteEllipsis: "삭제…",
      deleteTitle: "경기를 삭제할까요?",
      deleteWarning: "일정에서 이 경기가 제거됩니다. 되돌릴 수 없습니다.",
      delete: "삭제",
      deleting: "삭제 중…",
      noLocations: "장소 없음",
      status: "상태",
      tableTeam1: "팀 1",
      tableTeam2: "팀 2",
      tableLocation: "장소",
      tableScore: "스코어",
    },
    adminRegistrations: {
      addTitle: "등록 추가",
      editModalTitle: "등록 수정",
      addModalTitle: "등록 추가",
      deleteEllipsis: "삭제",
      deleteRegistration: "삭제",
      deleteModalTitle: "등록을 삭제할까요?",
      deleteModalBody:
        "이 선수의 부문 등록이 삭제됩니다. 되돌릴 수 없습니다.",
      deleteModalDeleting: "삭제 중…",
      totalCount: (count: number) => `총 ${count}건`,
      tableRegNumber: "#",
      tablePartner: "파트너 이름",
      tableMediaConsent: "미디어 동의",
      tableEngraving: "각인",
      emptyState: "등록 내역이 없습니다.",
    },
    categoryYears: {
      addTitle: "카테고리 추가",
      addModalTitle: "카테고리 추가",
      countLabel: (count: number) => `카테고리 ${count}개`,
      emptyState: "이 연도에 카테고리가 없습니다.",
    },
  },
} as const;
