export const adminPage = {
  en: {
    adminPage: {
      title: "Admin",
      tabs: {
        registrations: "Registrations",
        teams: "Teams",
        matches: "Matches",
        ball: "Ball",
        players: "Players",
        categories: "Category",
        prizes: "Prizes",
        admins: "Admin users",
        courtBookings: "Court Bookings",
        tumblers: "Tumblers",
      },
      actions: {
        addRegistration: "Add Registration",
        addPlayer: "Add Player",
        addAdminUser: "Add admin",
        save: "Save",
        saving: "Saving…",
        saveAndGenerate: "Save & Generate",
        generating: "Generating…",
        cancel: "Cancel",
        delete: "Delete",
        deleting: "Deleting…",
        add: "Add",
        adding: "Adding…",
        close: "Close",
        yes: "Yes",
        no: "No",
      },
      registrations: {
        empty: "No registrations",
        columns: {
          player: "Player",
          partner: "Partner",
          score: "Score",
          payment: "Payment",
          notes: "Notes",
          tumbler: "Tumbler",
        },
        modal: {
          title: "Manage Registration",
          addTitle: "Add Registration",
          playerSection: "Player",
          name: "Name (EN)",
          nameKo: "Name (KO)",
          partnerName: "Partner Name",
          nameOnEtransfer: "Name on e-Transfer",
          photoConsent: "Photo / video consent",
          notes: "Notes",
          category: "Category",
          paymentReceived: "Payment received",
          adminComments: "Admin comments",
        },
      },
      teams: {
        empty: "No teams",
        columns: {
          number: "#",
          player1: "Player 1",
          player2: "Player 2",
        },
        seedModal: {
          title: "Seed Teams",
          year: "Year",
          prelimFormat: "Prelim Format",
          roundRobin: "Round Robin",
          groupRoundRobin: "Group Round Robin",
          elimination: "Elimination",
          numberOfGroups: "Number of groups",
          selectTeamsPlaceholder: "Select teams…",
          seedLabel: "Seed",
          teamsCount: "teams",
          locked: "Seeding is locked — draws have already been published for this year",
        },
      },
      matches: {
        empty: "No matches",
        columns: {
          matchId: "Match",
          team1: "Team 1",
          team2: "Team 2",
          round: "Round",
          score: "Score",
          sets: "Sets",
          time: "Time",
          location: "Location",
        },
        modal: {
          title: "Edit Match",
          scoresSection: "Scores",
          set1: "Set 1",
          set2: "Set 2",
          set3: "Set 3",
          cancelled: "Cancelled",
          walkover: "Walkover",
          date: "Date",
          time: "Time",
          location: "Location",
          ball: "Ball",
          comment: "Comment",
        },
      },
      players: {
        empty: "No players",
        columns: {
          clubs: "Clubs",
          tournaments: "Tournaments",
        },
        modal: {
          editTitle: "Edit Player",
          addTitle: "Add Player",
          cannotDeleteTitle: "Cannot Delete Player",
        },
      },
      categories: {
        empty: "No categories",
        columns: {
          label: "Category",
          status: "Status",
          teams: "Teams",
        },
        modal: {
          editTitle: "Edit Category",
          statusLabel: "Status",
          playersTitle: "Registered Players",
          noPlayers: "No registrations for this category.",
          prelimFormat: "Prelim Format",
          roundRobin: "Round Robin",
          groupRoundRobin: "Group Round Robin",
          elimination: "Elimination",
        },
      },
      prizes: {
        empty: "No prize data",
        teamsUnit: "teams",
        bracketSuffix: "bracket",
        saveError: "Save failed",
        columns: {
          category: "Category",
          teams: "Teams",
          first: "1st",
          second: "2nd",
          third: "3rd",
          fourth: "4th",
          total: "Total",
        },
        modal: {
          title: "Edit Prize",
        },
      },
      admins: {
        empty: "No admin users",
        columns: {
          active: "Status",
          created: "Created",
        },
        activeLabel: "Active",
        inactiveLabel: "Inactive",
        modal: {
          editTitle: "Edit Admin User",
          addTitle: "Add Admin User",
          note: "The admin will set their password on first login.",
        },
      },
      courtBookings: {
        dateLabel: "Date",
        empty: "No courts",
        notAvailableLabel: "Not available",
        availableLabel: "Available",
        bookedLabel: "Booked",
        matchLabel: "Match",
        columns: {
          court: "Court",
          status: "Status",
          bookedBy: "Booked by",
          teams: "Teams",
        },
        manageTitle: "Manage booking",
        courtBookingNotesLabel: "Notes",
        matchSearchPlaceholder: "Enter player name to find match",
        cancelBookingLabel: "Cancel Booking",
      },
      tumblers: {
        columns: {
          tumbler: "Tumbler",
          stock: "Stock",
          status: "Status",
          player: "Player",
          tumblerChoice: "Tumbler",
          received: "Received",
          pickup: "Pickup club",
          pickupDetails: "Pickup details",
        },
        statusAvailable: "Available",
        statusFull: "Full",
        otherClub: "Other",
        noApplicants: "No applicants",
        pickupOtherPrefix: "Other",
        summaryTitle: "Distribution summary",
      },
      ball: {
        empty: "No balls assigned",
        rowCountSingular: "ball",
        rowCountPlural: "balls",
        columns: {
          player: "Player",
          match: "Match",
          received: "Received",
        },
      },
    },
  },
  ko: {
    adminPage: {
      title: "관리자",
      tabs: {
        registrations: "등록",
        teams: "팀",
        matches: "경기",
        ball: "공",
        players: "선수",
        categories: "카테고리",
        prizes: "상금",
        admins: "관리자 계정",
        courtBookings: "코트 예약",
        tumblers: "텀블러",
      },
      actions: {
        addRegistration: "등록 추가",
        addPlayer: "선수 추가",
        addAdminUser: "관리자 추가",
        save: "저장",
        saving: "저장 중…",
        saveAndGenerate: "저장 및 생성",
        generating: "생성 중…",
        cancel: "취소",
        delete: "삭제",
        deleting: "삭제 중…",
        add: "추가",
        adding: "추가 중…",
        close: "닫기",
        yes: "예",
        no: "아니오",
      },
      registrations: {
        empty: "등록 내역 없음",
        columns: {
          player: "선수",
          partner: "파트너",
          score: "점수",
          payment: "결제",
          notes: "메모",
          tumbler: "텀블러",
        },
        modal: {
          title: "등록 관리",
          addTitle: "등록 추가",
          playerSection: "선수",
          name: "이름 (EN)",
          nameKo: "이름 (KO)",
          partnerName: "파트너 이름",
          nameOnEtransfer: "이체 시 이름",
          photoConsent: "사진/영상 동의",
          notes: "메모",
          category: "카테고리",
          paymentReceived: "결제 완료",
          adminComments: "관리자 메모",
        },
      },
      teams: {
        empty: "팀 없음",
        columns: {
          number: "#",
          player1: "선수 1",
          player2: "선수 2",
        },
        seedModal: {
          title: "팀 시드 배정",
          year: "연도",
          prelimFormat: "예선 포맷",
          roundRobin: "라운드 로빈",
          groupRoundRobin: "그룹 라운드 로빈",
          elimination: "토너먼트",
          numberOfGroups: "그룹 수",
          selectTeamsPlaceholder: "팀 선택…",
          seedLabel: "시드",
          teamsCount: "팀",
          locked: "시드 배정이 잠겼습니다 — 올해 대진표가 이미 발표되었습니다",
        },
      },
      matches: {
        empty: "경기 없음",
        columns: {
          matchId: "경기",
          team1: "팀 1",
          team2: "팀 2",
          round: "라운드",
          score: "점수",
          sets: "세트",
          time: "시간",
          location: "장소",
        },
        modal: {
          title: "경기 편집",
          scoresSection: "점수",
          set1: "1세트",
          set2: "2세트",
          set3: "3세트",
          cancelled: "취소",
          walkover: "기권",
          date: "날짜",
          time: "시간",
          location: "장소",
          ball: "공",
          comment: "비고",
        },
      },
      players: {
        empty: "선수 없음",
        columns: {
          clubs: "클럽",
          tournaments: "대회 참가",
        },
        modal: {
          editTitle: "선수 편집",
          addTitle: "선수 추가",
          cannotDeleteTitle: "선수를 삭제할 수 없습니다",
        },
      },
      categories: {
        empty: "카테고리 없음",
        columns: {
          label: "카테고리",
          status: "상태",
          teams: "팀",
        },
        modal: {
          editTitle: "카테고리 편집",
          statusLabel: "상태",
          playersTitle: "등록된 선수",
          noPlayers: "이 카테고리에 등록된 선수가 없습니다.",
          prelimFormat: "예선 포맷",
          roundRobin: "라운드 로빈",
          groupRoundRobin: "그룹 라운드 로빈",
          elimination: "토너먼트",
        },
      },
      prizes: {
        empty: "상금 데이터 없음",
        teamsUnit: "팀",
        bracketSuffix: "구간",
        saveError: "저장 실패",
        columns: {
          category: "카테고리",
          teams: "팀",
          first: "1위",
          second: "2위",
          third: "3위",
          fourth: "4위",
          total: "합계",
        },
        modal: {
          title: "상금 편집",
        },
      },
      admins: {
        empty: "관리자 계정 없음",
        columns: {
          active: "상태",
          created: "생성일",
        },
        activeLabel: "활성",
        inactiveLabel: "비활성",
        modal: {
          editTitle: "관리자 편집",
          addTitle: "관리자  추가",
          note: "관리자는 첫 로그인 시 비밀번호를 설정합니다.",
        },
      },
      courtBookings: {
        dateLabel: "날짜",
        empty: "코트 정보 없음",
        notAvailableLabel: "해당 없음",
        availableLabel: "예약 가능",
        bookedLabel: "예약됨",
        matchLabel: "경기",
        columns: {
          court: "코트",
          status: "상태",
          bookedBy: "예약자",
          teams: "팀",
        },
        manageTitle: "코트 예약 관리",
        courtBookingNotesLabel: "메모",
        matchSearchPlaceholder: "이름을 입력하여 경기를 검색하세요",
        cancelBookingLabel: "예약 취소",
      },
      tumblers: {
        columns: {
          tumbler: "텀블러",
          stock: "재고",
          status: "상태",
          player: "선수",
          tumblerChoice: "텀블러",
          received: "수령 완료",
          pickup: "수령 클럽",
          pickupDetails: "픽업 세부 정보",
        },
        statusAvailable: "가능",
        statusFull: "마감",
        otherClub: "기타",
        noApplicants: "신청자 없음",
        pickupOtherPrefix: "Other",
        summaryTitle: "분배 요약",
      },
      ball: {
        empty: "배정된 공 없음",
        rowCountSingular: "공",
        rowCountPlural: "공",
        columns: {
          player: "선수",
          match: "경기",
          received: "수령 완료",
        },
      },
    },
  },
} as const;
