import { contactData } from "@/lib/contactData";
import { menuLabelForHref } from "./menu";

export const courtBookingPage = {
  en: {
    courtBookingPage: {
      heroTitle: menuLabelForHref("/court-booking", "en"),
      manageHeroTitle: "Manage booking",
      description:
        "Courts can be booked up to 7 days in advance. Available slots are first come, first served. Cancellations must be made through the official",
      chatLinkLabel: contactData.kakao.label,
      chatLinkSuffix: ".",
      chatHref: contactData.kakao.href,
      lookup: {
        emailLabel: "Email",
        button: "Search available courts",
        loading: "Looking up...",
        noResult: "No player found with this email.",
        error: "Something went wrong. Please try again.",
        noMatches: "No upcoming matches found for this account.",
      },
      cancel: {
        emailDescription: "Enter the email used when you booked the court.",
        searchButton: "Find my booking",
        cancelledTitle: "Your booking has been cancelled",
      },
      fields: {
        match: "Select match",
        matchPlaceholder: "Enter your name to find your match",
        matchBooked: "booked",
        court: "Court",
        courtAvailable: "Available",
        courtBooked: "Booked",
        courtCompleted: "Completed",
        courtExpired: "Expired",
        noCourts: "No courts for this date.",
        outsideWindow: "Courts can only be booked up to 7 days in advance.",
        courtsNotOpenYet: "Court booking opens on",
        date: "Date",
        notes: "Notes",
      },
      submit: "Book court",
      submitting: "Booking...",
      confirmation: {
        title: "Booking confirmed!",
        manageBooking: "Manage booking",
      },
      myBookings: "My bookings",
      noBookingsYet: "No courts booked yet.",
      cancellationPolicyLink: "See cancellation policy",
      errors: {
        match: "Please select a match.",
        court: "Please select a court.",
        date: "Please select a date.",
        failed: "Booking failed.",
        slotTaken: "Slot taken. Please select another.",
      },
    },
  },
  ko: {
    courtBookingPage: {
      heroTitle: menuLabelForHref("/court-booking", "ko"),
      manageHeroTitle: "예약 관리",
      description:
        "코트는 최대 7일 전부터 선착순으로 예약할 수 있습니다. 취소는 공식",
      chatLinkLabel: "카카오톡 오픈채팅",
      chatLinkSuffix: "을 통해 신청해 주세요.",
      chatHref: contactData.kakao.href,
      lookup: {
        emailLabel: "이메일",
        button: "예약 가능한 코트 검색",
        loading: "조회 중...",
        noResult: "해당 이메일로 등록된 선수를 찾을 수 없습니다.",
        error: "오류가 발생했습니다. 다시 시도해 주세요.",
        noMatches: "예정된 경기가 없습니다.",
      },
      cancel: {
        emailDescription: "코트를 예약할 때 사용한 이메일을 입력해 주세요.",
        searchButton: "예약 찾기",
        cancelledTitle: "예약이 취소되었습니다",
      },
      fields: {
        match: "경기 선택",
        matchPlaceholder: "이름을 입력하여 경기를 검색하세요",
        matchBooked: "예약됨",
        court: "코트",
        courtAvailable: "예약 가능",
        courtBooked: "예약됨",
        courtCompleted: "완료",
        courtExpired: "기한 종료",
        noCourts: "해당 날짜에 예약 가능한 코트가 없습니다.",
        outsideWindow: "오늘부터 7일 이내의 날짜만 예약 가능합니다.",
        courtsNotOpenYet: "코트 예약 시작일:",
        date: "날짜",
        notes: "메모",
      },
      submit: "코트 예약",
      submitting: "예약 중...",
      confirmation: {
        title: "예약이 완료되었습니다!",
        manageBooking: "예약 관리",
      },
      myBookings: "내 예약",
      noBookingsYet: "아직 예약된 코트가 없습니다.",
      cancellationPolicyLink: "취소 정책 보기",
      errors: {
        match: "경기를 선택하세요.",
        court: "코트를 선택하세요.",
        date: "날짜를 선택하세요.",
        failed: "예약에 실패했습니다.",
        slotTaken: "이미 예약된 슬롯입니다. 다른 날짜를 선택해 주세요.",
      },
    },
  },
} as const;
