export const drawsPage = {
  en: {
    drawsPage: {
      heroTitle: "Draws",
      tabs: {
        Draw: "Draws",
        Matches: "Matches",
        Results: "Results",
        Prizes: "Prizes",
        Timeline: "Schedule",
      },
      drawEmpty: "Draw coming soon",
      drawNoMatches: "No matches yet.",
      matchesEmpty: "Matches coming soon",
      matchesDateUnknown: "No date",
      resultsEmpty: "Results coming soon",
      prizesWhenDrawReady: "Prizes will be shown once draw data is entered for this year.",
      timelineWhenDrawReady: "Schedule will be shown once draw data is entered for this year.",
      noTimelineCategory: "No schedule data for this category.",
      teamNoHeader: "Team No.",
      drawStageLabel: "Round",
      drawStageFinalsBracket: "Finals",
      bracketPrevRound: "Previous round",
      bracketNextRound: "Next round",
      prizeTableBracket: "Bracket",
      prizeTableTeams: "Teams",
      prizeTable1st: "1st",
      prizeTable2nd: "2nd",
      prizeTable3rd: "3rd",
      prizeTable4th: "4th",
      prelims: {
        categoryCompleted: "Category completed",
        championRunnerUp: "Champion and runner-up",
        inProgress: "In progress",
        matchesWord: "matches",
        currentStage: "Current stage:",
        prelimsLeaderboard: "Prelims leaderboard",
        prelimsMatches: "Prelims matches",
        noPrelimsMatches: "No prelims matches yet.",
        tableRank: "Rank",
        tablePlayers: "Players",
        tableW: "W",
        tableL: "L",
        tableSD: "SD",
        tableGD: "GD",
        finalScoreLabel: "Final score",
        statsLegend: "W — Wins · L — Losses · SD — Set difference · GD — Game difference",
        allGroups: "All",
        championsByCategory: "Champions by category",
        championsCategoryCol: "Category",
        championsChampionCol: "Champion",
        championsRunnerUpCol: "Runner-up",
        championsEmpty: "No championship matches recorded for this year yet.",
        ariaCategoryStatus: "Category status",
        ariaPrelimsLeaderboard: "Prelims leaderboard",
        ariaPrelimsMatches: "Prelims matches",
      },
    },
  },
  ko: {
    drawsPage: {
      heroTitle: "대진",
      tabs: {
        Draw: "대진",
        Matches: "경기",
        Results: "결과",
        Prizes: "상금",
        Timeline: "일정",
      },
      drawEmpty: "대진 준비 중입니다",
      drawNoMatches: "아직 경기가 없습니다.",
      matchesEmpty: "경기 준비 중입니다",
      matchesDateUnknown: "날짜 미정",
      resultsEmpty: "결과 준비 중입니다",
      prizesWhenDrawReady: "올해 대진 데이터가 입력되면 상금 정보가 표시됩니다.",
      timelineWhenDrawReady: "올해 대진 데이터가 입력되면 일정이 표시됩니다.",
      noTimelineCategory: "이 카테고리의 일정 데이터가 없습니다.",
      teamNoHeader: "팀 번호",
      drawStageLabel: "라운드",
      drawStageFinalsBracket: "본선",
      bracketPrevRound: "이전 라운드",
      bracketNextRound: "다음 라운드",
      prizeTableBracket: "조",
      prizeTableTeams: "팀",
      prizeTable1st: "1위",
      prizeTable2nd: "2위",
      prizeTable3rd: "3위",
      prizeTable4th: "4위",
      prelims: {
        categoryCompleted: "종료된 부문",
        championRunnerUp: "우승·준우승",
        inProgress: "진행 중",
        matchesWord: "경기",
        currentStage: "현재 단계:",
        prelimsLeaderboard: "예선 순위",
        prelimsMatches: "예선 경기",
        noPrelimsMatches: "예선 경기가 아직 없습니다.",
        tableRank: "순위",
        tablePlayers: "선수",
        tableW: "승",
        tableL: "패",
        tableSD: "세트차",
        tableGD: "게임차",
        finalScoreLabel: "결승 스코어",
        statsLegend: "승 — 승수 · 패 — 패수 · 세트차 — 세트 득실 · 게임차 — 게임 득실",
        allGroups: "전체",
        championsByCategory: "부문별 우승",
        championsCategoryCol: "부문",
        championsChampionCol: "우승",
        championsRunnerUpCol: "준우승",
        championsEmpty: "올해 결승(우승) 기록이 아직 없습니다.",
        ariaCategoryStatus: "부문 상태",
        ariaPrelimsLeaderboard: "예선 순위표",
        ariaPrelimsMatches: "예선 경기",
      },
    },
  },
} as const;
