export const giveawayPage = {
  en: {
    giveawayPage: {
      heroTitle: "Giveaway",
      previewImageAlt: "2026 Tomlee Open tumbler options",
      searchDescription: "Enter the email address you used to register and select a tumbler option.",
      emailLookupLabel: "Your registration email",
      emailLookupPlaceholder: "Enter your email",
      lookupButton: "Next",
      lookingUpButton: "Looking up…",
      lookupNoResult: "No player found with that email.",
      lookupNotRegistered: "No registration found for this email.",
      lookupError: "Something went wrong. Please try again.",
      lookupMultipleFound: "Please select your name.",
      backButton: "Back",
      playerFoundLabel: "Logged in as",
      changeLookupLink: "Not you? Search again",
      choiceLabel: "Select your option",
      secondChoiceLabel: "Select your second option (admin only)",
      pickupLabel: "Pickup club",
      pickupPlaceholder: "Select a club",
      pickupOtherOption: "Other",
      pickupNoteLabel: "Pickup details",
      pickupNotePlaceholder: "Specify pickup detail (e.g. location, contact, etc.)",
      submitButton: "Submit",
      submittingButton: "Submitting…",
      updateButton: "Update",
      confirmationTitle: "Selection confirmed!",
      currentChoiceLabel: "Your selection",
      secondCurrentChoiceLabel: "Your second selection",
      changeButton: "Change selection",
      availableLabel: "Available",
      unavailableLabel: "Unavailable",
      errors: {
        choiceRequired: "Please select an option.",
        pickupRequired: "Please select a pickup club.",
        submissionFailed: "Submission failed. Please try again.",
        noRegistration: "No registration found for this player.",
        optionFull: "This option is no longer available.",
        secondOptionFull: "The second option is no longer available.",
      },
    },
  },
  ko: {
    giveawayPage: {
      heroTitle: "기념품",
      previewImageAlt: "2026 Tomlee Open 텀블러 옵션",
      searchDescription: "등록 시 사용한 이메일 주소를 입력하고 텀블러 옵션을 선택해 주세요.",
      emailLookupLabel: "등록 이메일",
      emailLookupPlaceholder: "이메일 입력",
      lookupButton: "다음",
      lookingUpButton: "검색 중…",
      lookupNoResult: "해당 이메일로 등록된 선수를 찾을 수 없습니다.",
      lookupNotRegistered: "해당 이메일의 등록 내역을 찾을 수 없습니다.",
      lookupError: "오류가 발생했습니다. 다시 시도해주세요.",
      lookupMultipleFound: "이름을 선택해 주세요.",
      backButton: "뒤로",
      playerFoundLabel: "로그인",
      changeLookupLink: "다른 이메일로 검색",
      choiceLabel: "옵션 선택",
      secondChoiceLabel: "두 번째 옵션 선택 (관리자)",
      pickupLabel: "수령 클럽",
      pickupPlaceholder: "클럽 선택",
      pickupOtherOption: "기타",
      pickupNoteLabel: "수령 정보",
      pickupNotePlaceholder: "수령 장소, 연락처 등을 입력해주세요.",
      submitButton: "제출",
      submittingButton: "제출 중…",
      updateButton: "변경",
      confirmationTitle: "선택 완료!",
      currentChoiceLabel: "선택한 옵션",
      secondCurrentChoiceLabel: "두 번째 선택",
      changeButton: "선택 변경",
      availableLabel: "가능",
      unavailableLabel: "마감",
      errors: {
        choiceRequired: "옵션을 선택해주세요.",
        pickupRequired: "수령 클럽을 선택해주세요.",
        submissionFailed: "제출에 실패했습니다. 다시 시도해주세요.",
        noRegistration: "해당 선수의 등록 내역을 찾을 수 없습니다.",
        optionFull: "이 옵션은 더 이상 선택할 수 없습니다.",
        secondOptionFull: "두 번째 옵션은 더 이상 선택할 수 없습니다.",
      },
    },
  },
} as const;
