import { menuLabelForHref } from "./menu";

export const recordsPage = {
  en: {
    recordsPage: {
      heroTitle: menuLabelForHref("/records", "en"),
      modalTitle: "Player record",
      emptyStateNoMatch: "No players match your search.",
      columnPlayer: "Player",
      columnClub: "Club",
      columnWins: "W",
      columnLosses: "L",
      columnWinRate: "Win %",
      matches: (count: number) => `${count} matches`,
      categories: (count: number) => `${count} ${count === 1 ? "category" : "categories"}`,
      sortByWins: "Wins",
      sortByWinRate: "Win rate",
      sortByTitles: "Titles",
      sortByMatches: "Matches",
      statWinRate: "Win rate",
      statRecord: "Wins / Losses",
      statMatches: "Matches",
      statCategories: "Categories",
      titlesHeading: "Titles",
      matchHistoryHeading: "Match history",
      noTitles: "No titles yet.",
    },
  },
  ko: {
    recordsPage: {
      heroTitle: menuLabelForHref("/records", "ko"),
      modalTitle: "선수 기록",
      emptyStateNoMatch: "검색 결과와 일치하는 선수가 없습니다.",
      columnPlayer: "선수",
      columnClub: "클럽",
      columnWins: "승",
      columnLosses: "패",
      columnWinRate: "승률",
      matches: (count: number) => `${count}경기`,
      categories: (count: number) => `${count}개 종목`,
      sortByWins: "승수",
      sortByWinRate: "승률",
      sortByTitles: "우승수",
      sortByMatches: "총 경기 수",
      statWinRate: "승률",
      statRecord: "전적",
      statMatches: "경기",
      statCategories: "종목",
      titlesHeading: "우승 기록",
      matchHistoryHeading: "경기 기록",
      noTitles: "아직 우승 기록이 없습니다.",
    },
  },
} as const;
