export const registrationForm = {
  en: {
    registrationForm: {
      sections: {
        personalDetails: "Personal details",
        tournamentDetails: "Tournament details",
        mediaConsent: "Media consent",
        tumblerEngraving: "Tumbler engraving",
        paymentInformation: "Payment information",
      },
      fields: {
        fullNameEn: "Full name (English)",
        fullNameKo: "Full name (Korean)",
        email: "Email",
        phone: "Phone number",
        ntrp: "NTRP level",
        clubs: "Club(s)",
        categories: "Categories",
        searchCategoriesPlaceholder: "Select categories",
        searchClubsPlaceholder: "Select clubs",
        partnerName: "Partner name",
        engravingText: "Engraving text",
        engravingPreviewPlaceholder: "Tumbler preview",
        nameOnEtransfer: "Name on e-transfer",
        status: "Registration status",
      },
      buttons: {
        submit: "Submit",
        submitting: "Submitting...",
        saveChanges: "Save changes",
        lookUp: "Look up",
        lookingUp: "Looking up…",
        back: "Back",
      },
      page: {
        returningRegistrantPrompt: "Returning registrant?",
        editLinkLabel: "Edit",
        editLinkSuffix: "your registration.",
        lookupDescription: "Enter your registered email address to view and edit your registration.",
        lookupEmailLabel: "Email",
        lookupNoResult: "No registration found.",
      },
      options: {
        selectLevel: "Select level",
        statusConfirmed: "Confirmed",
        statusCancelled: "Cancelled",
      },
      helper: {
        etransferSent: "I have sent the e-transfer",
        mediaConsent: "I agree to photos and videos being used for tournament media and social channels.",
        tumblerEngraving: "I would like a personalized tumbler engraving.",
      },
      summary: {
        line: "{count} categories · {total}",
        etransferLabel: "E-transfer:",
        copyEmail: "Copy",
        emailCopied: "Copied",
      },
      success: {
        completed: "Registration complete.",
        body: "Your registration has been received. The organizer will be in touch with further details.",
      },
      errors: {
        required: "Required",
        invalidEmail: "Enter a valid email address",
        invalidPhone: "Enter a valid 10-digit phone number",
        selectAtLeastOneCategory: "Select at least one category",
        partnerNameRequired: "Partner name required",
        mediaConsentRequired: "Media consent is required",
        nameOnEtransferRequired: "Name on e-transfer is required",
        etransferSentRequired: "Confirm that you have sent the e-transfer",
        registrationFailed: "Registration failed",
      },
    },
  },
  ko: {
    registrationForm: {
      sections: {
        personalDetails: "개인 정보",
        tournamentDetails: "대회 정보",
        mediaConsent: "미디어 동의",
        tumblerEngraving: "텀블러 각인",
        paymentInformation: "결제 정보",
      },
      fields: {
        fullNameEn: "영문 이름",
        fullNameKo: "한글 이름",
        email: "이메일",
        phone: "휴대폰 번호",
        ntrp: "NTRP 레벨",
        clubs: "클럽",
        categories: "카테고리",
        searchCategoriesPlaceholder: "카테고리 선택",
        searchClubsPlaceholder: "클럽 검색",
        partnerName: "파트너 이름",
        engravingText: "각인 문구",
        engravingPreviewPlaceholder: "텀블러 미리보기",
        nameOnEtransfer: "이체자명",
        status: "등록 상태",
      },
      buttons: {
        submit: "제출",
        submitting: "제출 중...",
        saveChanges: "변경 저장",
        lookUp: "조회",
        lookingUp: "조회 중…",
        back: "뒤로",
      },
      page: {
        returningRegistrantPrompt: "이미 등록하셨나요?",
        editLinkLabel: "등록 수정",
        editLinkSuffix: "",
        lookupDescription: "등록하신 이메일 주소를 입력하면 등록 내역을 확인하고 수정할 수 있습니다.",
        lookupEmailLabel: "이메일",
        lookupNoResult: "등록 내역을 찾을 수 없습니다.",
      },
      options: {
        selectLevel: "레벨 선택",
        statusConfirmed: "확정",
        statusCancelled: "취소",
      },
      helper: {
        etransferSent: "이체를 완료했습니다",
        mediaConsent: "대회 미디어 및 소셜 채널에 사진/영상 사용에 동의합니다.",
        tumblerEngraving: "텀블러 각인을 신청합니다.",
      },
      summary: {
        line: "카테고리 {count}개 · {total}",
        etransferLabel: "이체:",
        copyEmail: "복사",
        emailCopied: "복사됨",
      },
      success: {
        completed: "등록이 완료되었습니다.",
        body: "등록이 접수되었습니다. 대회 관련 안내는 추후 별도로 전달될 예정입니다.",
      },
      errors: {
        required: "필수 입력 항목입니다",
        invalidEmail: "올바른 이메일 주소를 입력해 주세요",
        invalidPhone: "올바른 전화번호를 입력해 주세요.",
        selectAtLeastOneCategory: "카테고리를 최소 1개 선택해 주세요",
        partnerNameRequired: "파트너 이름을 입력해 주세요",
        mediaConsentRequired: "미디어 동의는 필수입니다",
        nameOnEtransferRequired: "이체자명을 입력해 주세요",
        etransferSentRequired: "이체 완료 여부를 확인해 주세요",
        registrationFailed: "등록에 실패했습니다",
      },
    },
  },
} as const;
