export const shared = {
  en: {
    shared: {
      sectionTitles: {
        otherClubs: "Other clubs",
      },
      buttons: {
        back: "← Back",
        contact: "Contact",
      },
      form: {
        email: "Email",
        fullNameEn: "Full name (English)",
        fullNameKo: "Full name (Korean)",
        phone: "Phone number",
        ntrp: "NTRP level",
        clubs: "Club(s)",
        notes: "Notes",
        gender: "Gender",
      },
      genderOptions: {
        unknown: "Unknown",
        male: "Male",
        female: "Female",
      },
      labels: {
        coach: "Coach",
        category: "Category",
        year: "Year",
        club: "Club",
        allCategories: "Category",
        allClubs: "Club",
        round: "Round",
        allRounds: "Round",
        seed: "Seed",
        allSeeds: "Seed",
        date: "Date",
        status: "Status",
        allStatuses: "All",
        all: "All",
        allYears: "Year",
        total: "Total",
      },
      aria: {
        viewDetail: (name: string) => `View ${name} details`,
        contact: (name: string) => `Contact ${name}`,
        visit: (name: string) => `Visit ${name}`,
      },
      modal: {
        close: "Close",
      },
    },
    emptyStates: {
      noMatches: "No matches on this date.",
      noResults: "No results for this category.",
      noPlayers: "No players yet.",
    },
  },
  ko: {
    shared: {
      sectionTitles: {
        otherClubs: "다른 클럽",
      },
      buttons: {
        back: "← 뒤로",
        contact: "연락하기",
      },
      form: {
        email: "이메일",
        fullNameEn: "영문 이름",
        fullNameKo: "한글 이름",
        phone: "휴대폰 번호",
        ntrp: "NTRP 레벨",
        clubs: "클럽",
        notes: "메모",
        gender: "성별",
      },
      genderOptions: {
        unknown: "미상",
        male: "남성",
        female: "여성",
      },
      labels: {
        coach: "코치",
        category: "카테고리",
        year: "연도",
        club: "클럽",
        allCategories: "카테고리",
        allClubs: "클럽",
        round: "라운드",
        allRounds: "라운드",
        seed: "시드",
        allSeeds: "시드",
        date: "날짜",
        status: "상태",
        allStatuses: "전체 상태",
        all: "전체",
        allYears: "연도",
        total: "총",
      },
      aria: {
        viewDetail: (name: string) => `${name} 자세히 보기`,
        contact: (name: string) => `${name} 연락`,
        visit: (name: string) => `${name} 방문`,
      },
      modal: {
        close: "닫기",
      },
    },
    emptyStates: {
      noMatches: "이 날짜에 경기가 없습니다.",
      noResults: "이 카테고리에 결과가 없습니다.",
      noPlayers: "등록된 선수가 없습니다.",
    },
  },
} as const;
